name: Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  
  # Run workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "github-metrics"
  github-metrics:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: 
      name: production
      
    permissions:
      contents: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_EMBED_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://github.com/fmukhlis
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_detailed: yes
